### ISSUE TITLE
MCQs Quizes

### ISSUE THREAD

**Issue by dilshad-geol** [joe-c-29b/StatisticalAnalyses#1]
Can you share the MCQs and short quiz tests which you've done for this work? I mean related to R. If you upload the pdfs for the outputs or the codes, it will be really helpful.  I really need help. Thank you

**Comment by joe-c-29b** [comment]
Most of these are duplicates of each other, so the .rmd files still have most of the prompt questions with them.  They are all based out of the https://github.com/hadley/r4ds textbook, so a lot of the additional data and info can be found there, unfortunately the .pdfs themselves can't be posted because that would be a breach of my school's policies.  

I bounce between 4 computers due to work and travel so this is where I have had to save a lot of my coursework.
I keep the repo public because I have a pretty pathetic portfolio as it is (still pretty new to the field).
If you have any specific items that need clarification or comments on how I could improve I am happy to talk about any of it, I just can't post the original assignments because I am still a student in the program.

**Comment by dilshad-geol** [comment]
Okay, great..! In DBMS repo, you haven't uploaded the Assignment 3. Can you share that?
